### ISSUE TITLE
Exhaust version 1.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by Alewo111** [kashike/Exhaust#2]
This version is currently not working as Intake version from 4.0 up are currently broken.

Add back 1.0.0-SNAPSHOT ?

**Comment by kashike** [comment]
I've deployed 1.0.0-SNAPSHOT to the repository.
What issues are you encountering with 4.0?

**Comment by Alewo111** [comment]
Thank you for your help. This is the error I get in my console:
```
21:40:49 [WARNING] Exception encountered when loading plugin: BungeeCore
com.sk89q.intake.parametric.IllegalParameterException: Can't finding a binding for the parameter type 'class com.sk89q.intake.argument.CommandContext'
    at com.sk89q.intake.parametric.ArgumentParser$Builder.addParameter(ArgumentParser.java:288)
    at com.sk89q.intake.parametric.MethodCallable.create(MethodCallable.java:107)
    at com.sk89q.intake.parametric.ParametricBuilder.build(ParametricBuilder.java:149)
    at com.sk89q.intake.parametric.ParametricBuilder.registerMethodsAsCommands(ParametricBuilder.java:134)
    at com.sk89q.intake.fluent.DispatcherNode.registerMethods(DispatcherNode.java:72)
    at it.sphx.bungeecore.BungeeCore.registerCommands(BungeeCore.java:140)
    at it.sphx.bungeecore.BungeeCore.onEnable(BungeeCore.java:117)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
